Crypto3 and libs/actor/zk updated #83
NilFoundation/proof-producer pull request #84
Opened 2024-03-03 20:18 UTC by ETatuzova

2024-03-03 20:19 UTC, ETatuzova commented
TODO: add JSON generation

2024-03-04 05:04 UTC, x-mass requested changes
Don't forget to run clang before commiting, otherwise [check](https://github.com/NilFoundation/proof-producer/actions/runs/8132780602/job/22223606007) will not pass. It has a command to run in output log

2024-03-04 05:04 UTC, x-mass commented on bin/proof-generator/include/nil/proof-generator/arg_parser.hpp
> +            HashesVariant hash_type;
It's not good we don't have default `hash_type`. It will fail if user doesn't provide any as well

2024-03-04 05:04 UTC, x-mass commented on bin/proof-generator/include/nil/proof-generator/prover.hpp
> +                table_description_ = table_description;
.emplace()
The type could have no assignment operator

2024-03-04 05:04 UTC, x-mass commented on bin/proof-generator/src/arg_parser.cpp
> -#undef X
The goal of these lines was to reduce boilerplate code amount. Did you try to add new types to `HASH_TYPES` instead of manually creating operators?

2024-03-04 05:04 UTC, x-mass commented on bin/proof-generator/src/main.cpp
> +    std::cout << "Hash wrapper" << std::endl;
Debug print

2024-03-04 05:04 UTC, x-mass commented on bin/proof-generator/src/main.cpp
> +    std::cout << prover_options->circuit_file_path << std::endl;
ditto

2024-03-04 05:04 UTC, x-mass commented on bin/proof-generator/include/nil/proof-generator/prover.hpp
> -                plonk_arithmetization_params<WitnessColumns, PublicInputColumns, ConstantColumns, SelectorColumns>;
Params are still left in arg_parser, should be removed there as well

2024-05-07 18:48 UTC, x-mass approved these changes
🔥

2024-05-07 18:51 UTC, merged